image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make 
  script: 
    - make
  artifacts:
    paths:
      - a.out
  cache:
    paths:
      - "*.o"

test:
  stage: test
  script:
    - "[[ $(./test.sh a.out | grep 100% -o | wc -l) == $(ls testCases/test*|  wc -l) ]]"
